import { Trip, ActivityType, TripBudget } from './trip.types';

export const MOCK_TRIP: Trip = {
  id: 'mock-trip-dalat-2026',
  destination: 'Đà Lạt, Việt Nam',
  checkIn: '2026-03-15T00:00:00Z',
  checkOut: '2026-03-18T00:00:00Z',
  adults: 2,
  children: 0,
  budget: TripBudget.MODERATE,
  preferences: ['Thiên nhiên', 'Cà phê', 'Lãng mạn', 'Ẩm thực'],
  createdAt: new Date().toISOString(),
  days: [
    {
      id: 'day-1',
      dayNumber: 1,
      date: '2026-03-15T00:00:00Z',
      activities: [
        {
          id: 'act-1-1',
          name: 'Nhận phòng tại Ana Mandara Villas Dalat Resort',
          description: 'Nhận phòng villa sang trọng với view núi đồi thơ mộng và không khí se lạnh đặc trưng',
          time: '14:00',
          type: ActivityType.CHECK_IN,
          location: 'Ana Mandara Villas, Lê Lai, Đà Lạt',
          price: 'Đã bao gồm',
          displayOrder: 0,
          imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-1-2',
          name: 'Dạo quanh Hồ Xuân Hương',
          description: 'Tản bộ quanh hồ trái tim, ngắm hoàng hôn và chụp ảnh với hoa mimosa vàng rực',
          time: '16:30',
          type: ActivityType.ACTIVITY,
          location: 'Hồ Xuân Hương, Trung tâm Đà Lạt',
          price: 'Miễn phí',
          displayOrder: 1,
          imageUrl: 'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-1-3',
          name: 'Ăn tối tại Long Hoa Restaurant',
          description: 'Thưởng thức lẩu nấm rừng đặc sản, thịt nướng lá lốt và rau rừng tươi ngon',
          time: '18:30',
          type: ActivityType.DINING,
          location: 'Long Hoa, 33 Bùi Thị Xuân, Đà Lạt',
          price: '350.000 VNĐ/người',
          displayOrder: 2,
          imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-1-4',
          name: 'Dạo chợ đêm Đà Lạt',
          description: 'Khám phá chợ đêm sầm uất, thử bánh tráng nướng, sữa đậu nành nóng và mua đặc sản',
          time: '20:00',
          type: ActivityType.EXPERIENCE,
          location: 'Chợ Đêm Đà Lạt, Nguyễn Thị Minh Khai',
          price: '100.000 VNĐ',
          displayOrder: 3,
          imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=600',
        }
      ]
    },
    {
      id: 'day-2',
      dayNumber: 2,
      date: '2026-03-16T00:00:00Z',
      activities: [
        {
          id: 'act-2-1',
          name: 'Săn mây tại Đồi Chè Cầu Đất',
          description: 'Ngắm bình minh giữa đồi chè xanh mướt và săn mây trôi ngoạn mục',
          time: '05:30',
          type: ActivityType.EXPERIENCE,
          location: 'Đồi Chè Cầu Đất, cách Đà Lạt 18km',
          price: '50.000 VNĐ vé vào',
          displayOrder: 0,
          imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-2-2',
          name: 'Ăn sáng tại Bánh Mì Phượng',
          description: 'Thưởng thức bánh mì pate nóng hổi với trứng ốp la và cà phê sữa đá',
          time: '08:00',
          type: ActivityType.DINING,
          location: 'Bánh Mì Phượng, 37 Phan Bội Châu',
          price: '35.000 VNĐ/người',
          displayOrder: 1,
          imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-2-3',
          name: 'Tham quan Chùa Linh Phước',
          description: 'Khám phá chùa gốm sứ nổi tiếng với kiến trúc độc đáo và tranh khảm rực rỡ',
          time: '10:00',
          type: ActivityType.EXPERIENCE,
          location: 'Chùa Linh Phước, Trại Mát, Đà Lạt',
          price: 'Miễn phí',
          displayOrder: 2,
          imageUrl: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-2-4',
          name: 'Ăn trưa tại Lẩu Bò Tơ Tây Nguyên',
          description: 'Thưởng thức lẩu bò tơ đặc sản, thịt bò tươi ngon kèm rau rừng thơm mát',
          time: '12:30',
          type: ActivityType.DINING,
          location: 'Nguyễn Trãi, Đà Lạt',
          price: '280.000 VNĐ/người',
          displayOrder: 3,
          imageUrl: 'https://images.unsplash.com/photo-1588956455728-317ea8b48ce2?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-2-5',
          name: 'Chill tại Cà phê Mê Linh',
          description: 'Thư giãn với ly cà phê rang mộc ngắm view thành phố từ trên cao',
          time: '15:00',
          type: ActivityType.RELAXATION,
          location: 'Cà Phê Mê Linh, Phan Bội Châu',
          price: '45.000 VNĐ/ly',
          displayOrder: 4,
          imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-2-6',
          name: 'Thăm Crazy House (Biệt thự Hằng Nga)',
          description: 'Khám phá công trình kiến trúc siêu thực kỳ lạ với cây cối và hang động độc đáo',
          time: '16:30',
          type: ActivityType.EXPERIENCE,
          location: 'Huyền Trân Công Chúa, Đà Lạt',
          price: '60.000 VNĐ/người',
          displayOrder: 5,
          imageUrl: 'https://images.unsplash.com/photo-1583721292810-a56f4d07b8db?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-2-7',
          name: 'Ăn tối BBQ tại Trung Nguyên Legend',
          description: 'Buffet nướng phong cách Hàn Quốc với thịt heo, bò, hải sản tươi sống',
          time: '19:00',
          type: ActivityType.DINING,
          location: 'Trung Nguyên Legend, Trần Phú',
          price: '299.000 VNĐ/người',
          displayOrder: 6,
          imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
        }
      ]
    },
    {
      id: 'day-3',
      dayNumber: 3,
      date: '2026-03-17T00:00:00Z',
      activities: [
        {
          id: 'act-3-1',
          name: 'Ăn sáng tại resort',
          description: 'Buffet sáng tại nhà hàng resort với các món Âu, Á và đặc sản Đà Lạt',
          time: '07:30',
          type: ActivityType.DINING,
          location: 'Ana Mandara Restaurant',
          price: 'Đã bao gồm',
          displayOrder: 0,
          imageUrl: 'https://images.unsplash.com/photo-1533777324565-a040eb52facd?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-3-2',
          name: 'Tham quan Thiền Viện Trúc Lâm',
          description: 'Đi cáp treo ngắm cảnh toàn thành phố, tham quan chùa Trúc Lâm yên bình',
          time: '09:00',
          type: ActivityType.EXPERIENCE,
          location: 'Hồ Tuyền Lâm, Đà Lạt',
          price: '90.000 VNĐ (cáp treo khứ hồi)',
          displayOrder: 1,
          imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-3-3',
          name: 'Chèo thuyền kayak Hồ Tuyền Lâm',
          description: 'Trải nghiệm chèo kayak giữa hồ xanh ngắt và rừng thông bao quanh',
          time: '11:00',
          type: ActivityType.ACTIVITY,
          location: 'Hồ Tuyền Lâm',
          price: '150.000 VNĐ/thuyền',
          displayOrder: 2,
          imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-3-4',
          name: 'Ăn trưa tại Quán Gió Đà Lạt',
          description: 'Thưởng thức các món Việt fusion, pizza lò gạch và kem dâu Đà Lạt',
          time: '13:00',
          type: ActivityType.DINING,
          location: 'Quán Gió, Yersin, Đà Lạt',
          price: '200.000 VNĐ/người',
          displayOrder: 3,
          imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-3-5',
          name: 'Check-out và mua sắm đặc sản',
          description: 'Trả phòng và ghé chợ Đà Lạt mua dâu tây, atiso, mứt, bơ, socola làm quà',
          time: '15:00',
          type: ActivityType.CHECK_OUT,
          location: 'Chợ Đà Lạt, Nguyễn Thị Minh Khai',
          price: '500.000 VNĐ (mua sắm)',
          displayOrder: 4,
          imageUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&q=80&w=600',
        },
        {
          id: 'act-3-6',
          name: 'Di chuyển về sân bay Liên Khương',
          description: 'Taxi hoặc xe hợp đồng từ Đà Lạt về sân bay Liên Khương (30km - 45 phút)',
          time: '16:30',
          type: ActivityType.TRANSPORTATION,
          location: 'Sân bay Liên Khương',
          price: '300.000 VNĐ/xe taxi',
          displayOrder: 5,
          imageUrl: 'https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?auto=format&fit=crop&q=80&w=600',
        }
      ]
    }
  ]
};
